-- ##################################################################
-- #  MIGRATION 1: SCHEMA DI AUTENTICAZIONE E AUTORIZZAZIONE (AUTH)
-- ##################################################################

-- ### 1. TABELLA COMPANIES ###
CREATE TABLE companies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

-- ### 2. TABELLA USER_PROFILES (Anagrafica) ###
CREATE TABLE user_profiles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL,

    CONSTRAINT fk_user_profiles_to_company FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE RESTRICT
);
CREATE INDEX idx_user_profiles_email ON user_profiles(email);


-- ### 3. TABELLA USER_CREDENTIALS ###
CREATE TABLE user_credentials (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_profile_id BIGINT NOT NULL,
    password VARCHAR(255),
    provider VARCHAR(50) NOT NULL,
    provider_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL,

    CONSTRAINT fk_credentials_to_profile FOREIGN KEY(user_profile_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
    CONSTRAINT uq_provider_provider_id UNIQUE (provider, provider_id)
);
CREATE INDEX idx_user_credentials_provider_provider_id ON user_credentials(provider, provider_id);


-- ### 4. TABELLA ROLES ###
CREATE TABLE roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);


-- ### 5. TABELLA PERMISSIONS ###
CREATE TABLE permissions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);


-- ### 6. TABELLA DI JOIN PROFILI-RUOLI (Many-To-Many) ###
CREATE TABLE user_profile_roles (
    user_profile_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_profile_id, role_id),

    CONSTRAINT fk_profile_roles_to_profile FOREIGN KEY(user_profile_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_profile_roles_to_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE
);


-- ### 7. TABELLA DI JOIN RUOLI-PERMESSI (Many-To-Many) ###
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_role_permissions_to_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_to_permission FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);